export const Status = {
    idle: "idle",
    loading: "loading",
    succeeded: "succeeded",
    failed: "failed",
};

export const CompanyStatus = [
    {
        value: 0,
        label: "Đang chờ xác nhận",
    },
    {
        value: 1,
        label: "Đang hoạt động",
    },
    {
        value: 2,
        label: "Vô hiệu hóa",
    },
];

export const Currency = [
    {
        value: 0,
        label: "VND",
        rate: 1,
    },
    {
        value: 1,
        label: "USD",
        rate: 24400,
    },
];

export const Role = {
    Faculty: "Faculty",
    Business: "Business",
    Student: "Student",
};

export const SalaryType = [
    { value: 1, label: "Thương Lượng" },
    { value: 2, label: "Từ - đến" },
    { value: 3, label: "Lên tới" },
    { value: 4, label: "Tối thiểu" },
];

export const WorkingType = [
    { value: 1, label: "At office" },
    { value: 2, label: "Remote" },
    { value: 3, label: "Flexible" },
];

export const JobSkill = [
    "Agile",
    "Android",
    "Angular",
    "AngularJS",
    "ASP.NET",
    "AWS",
    "Blockchain",
    "Bridge Engineer",
    "Business Analyst",
    "C#",
    "C++",
    "C language",
    "Cloud",
    "Cocos",
    "CSS",
    "Data Analyst",
    "Database",
    "Designer",
    "DevOps",
    "Django",
    "Embedded",
    "English",
    "ERP",
    "Flutter",
    "Games",
    "Golang",
    "HTML5",
    "iOS",
    "IT Support",
    "J2EE",
    "Japanese",
    "Java",
    "JavaScript",
    "JQuery",
    "JSON",
    "Kotlin",
    "Laravel",
    "Linux",
    "Magento",
    "Manager",
    "MVC",
    "MySQL",
    ".NET",
    "Networking",
    "NodeJS",
    "NoSQL",
    "Objective C",
    "OOP",
    "Oracle",
    "PHP",
    "PostgreSql",
    "Product Manager",
    "Project Manager",
    "Python",
    "QA QC",
    "ReactJS",
    "React Native",
    "Ruby",
    "Ruby on Rails",
    "SAP",
    "Scala",
    "Scrum",
    "Sharepoint",
    "Software Architect",
    "Spring",
    "SQL",
    "Swift",
    "System Admin",
    "System Engineer",
    "Team Leader",
    "Tester",
    "TypeScript",
    "UI-UX",
    "Unity",
    "VueJS",
    "Wordpress",
    "Xamarin",
];
